--- 
- hosts: all
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
   - name: Intsall appache server
     action: yum name=httpd state=installed
     async: 300
     poll: 3

     notify: restarted httpd
  handlers:
   - name: restarted httpd
     action: service name=httpd state=restarted

