---
- hosts: venky
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  tasks:
    - name: Install https packages
      action: yum name=httpd state=installed
      notify: Restarted httpd
  handlers:
     - name: Restarted httpd
       action: service name=httpd state=restarted

  
