---
- hosts: venky
  user: ansible
  sudo: yes
  connection: ssh
  gather_facts: no
  vars_files:
   - vars.yml
  tasks:
    - name: Install https packages
      action: yum name='{{pkname}}' state=installed
 

  
